# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  # TODO: add import restrictions between layers (e.g., presentation -> infrastructure)

linter:
  rules:
    avoid_relative_lib_imports: true
    prefer_relative_imports: false
    # place additional lint rules here

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 40
    source-lines-of-code: 200
