name: toolmape
description: "ToolMAPE es tu app aliada en el día a día minero. Calcula precios de oro y minerales, accede a herramientas gratuitas, infórmate con resúmenes y blogs actualizados, y conecta con consultores expertos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^5.0.0
  dart_code_metrics: ^4.19.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/LoadingTrazMAPE.png
